version: "3.8"

services:
  linklens:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - howl-net

networks:
  howl-net:
    driver: bridge
