version: "3.8"

services:
  springapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Dcom.sun.jndi.ldap.object.trustURLCodebase=true -Dcom.sun.jndi.rmi.object.trustURLCodebase=true -Dlog4j2.formatMsgNoLookups=false
    restart: unless-stopped
    networks:
      - howl-net

networks:
  howl-net:
    driver: bridge
